export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
export const LOGIN_SUCCESSED = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT = 'LOGOUT'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESSED = 'REGISTER_SUCCESSED'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const UPDATE_STATUS_ERROR = 'UPDATE_STATUS_ERROR'
export const SHOW_MODAL = 'SHOW_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const SHOW_CREATE_ACC_MODAL = 'SHOW_CREATE_ACC_MODAL'
export const SHOW_LOGIN_ACC_MODAL = 'SHOW_LOGIN_ACC_MODAL'










